apiVersion: apps/v1 # i se Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: idc-servicio-solicitud
  labels:
    name: "servicio-solicitud"
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: solicitud
  replicas: 1
  strategy:
    type: RollingUpdate
  template:   # Plantilla que define el container
    metadata:
      labels:
        app: solicitud
    spec:
      containers:
      - name: idc-servicio-solicitud
        image: dmcontainerregister.azurecr.io/idc-servicio-solicitud-dev-local:1.0.0.3
        ports:
          - containerPort: 8505
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s-dev
          - name: SERVER_PORT
            value: "8505"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        nodo: master

