apiVersion: apps/v1 # i se Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: idc-servicio-estaciones
  labels:
    name: "servicio-estaciones"
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: estaciones
  replicas: 1
  strategy:
    type: RollingUpdate
  template:   # Plantilla que define el container
    metadata:
      labels:
        app: estaciones
    spec:
      containers:
      - name: idc-servicio-estaciones
        image: dmcontainerregister.azurecr.io/idc-servicio-estaciones-dev:1.0.0.42
        ports:
          - containerPort: 8513
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s-dev
          - name: SERVER_PORT
            value: "8513"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        nodo: master

