apiVersion: v1
kind: Service
metadata:
  name: idc-servicio-zuul-server
  labels:
     app: zuul
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30006
    protocol: TCP
  selector:
     app: zuul

