apiVersion: v1
kind: Service
metadata:
  name: idc-rabbitmq38-alpine
  labels:
     app: rabbit
     project: broker
spec:
  type: NodePort
  ports:
  - name: port1
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: port2
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: port3
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: port4
    port: 15671
    protocol: TCP
    targetPort: 15671
  - name: port5
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: port6
    port: 15672
    nodePort: 31000
    protocol: TCP
  selector:
     app: rabbit
     project: broker

