apiVersion: v1
kind: Service
metadata:
  name: idc-eureka-server
  labels:
     app: eureka
     project: register
spec:
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30005
    protocol: TCP
  selector:
     app: eureka
     project: register

