apiVersion: v1
kind: Service
metadata:
  name: idc-servicio-consultae4
  labels:
     app: consultae4
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30010
    protocol: TCP
  selector:
     app: consultae4

