apiVersion: apps/v1 # i se Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: idc-zipkin-server-memory
  labels:
    name: "zipkin-server"
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: zipkin
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:   # Plantilla que define los containers
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: idc-zipkin-server-memory
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
      nodeSelector:
        nodo: master

